# Generated by Django 3.1.5 on 2021-01-27 17:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('nome_paciente', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('semCPF', models.BooleanField(default=False)),
                ('cns', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('dt_nascimento', models.DateField()),
                ('dt_1_sintomas', models.DateField()),
                ('dt_ini_isolamento', models.DateField()),
                ('dt_fim_isolamento', models.CharField(default='AUTOMÁTICO', max_length=20)),
                ('responsavel_pct', models.CharField(choices=[('Paciente', 'PACIENTE'), ('Responsável', 'RESPONSÁVEL')], default='', max_length=20)),
                ('grau_parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('sintomas', multiselectfield.db.fields.MultiSelectField(choices=[('Assintomático', 'ASSINTOMÁTICO'), ('Astenia', 'ASTENIA'), ('Cefaléia', 'CEFALÉIA'), ('Dispinéia', 'DISPINÉIA'), ('Distúrbios Gastrintestinais', 'DISTÚRBIOS GASTRINTESTINAIS'), ('Distúrbios Gustativos', 'DISTÚRBIOS GUSTATIVOS'), ('Distúrbios Olfativos', 'DISTÚRBIOS OLFATIVOS'), ('Dor de Garganta', 'DOR DE GARGANTA'), ('Dorsalgia', 'DORSALGIA'), ('Febre', 'FEBRE'), ('Mialgia', 'MIALGIA'), ('Odinofagia', 'ODINOFAGIA'), ('Tosse', 'TOSSE'), ('Outros', 'OUTROS')], max_length=175)),
                ('condicoes', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Doenças respiratórias crônicas descompensadas', 'DOENÇAS RESPIRATÓRIAS CRÔNICAS DESCOMPENSADAS'), ('Doenças cardiácas crônicas', 'DOENÇAS CARDIÁCAS CRÔNICAS'), ('Diabetes', 'DIABETES'), ('Doenças renais crônicas em estágios avançados', 'DOENÇAS RENAIS CRÔNICAS EM ESTÁGIOS AVANÇADOS'), ('Gestante de alto risco', 'GESTANTE DE ALTO RISCO'), ('Imunossupressão', 'IMUNOSSUPRESSÃO'), ('Portador de doenças cromossômicas', 'PORTADOR DE DOENÇAS CROMOSSÔMICAS')], max_length=200, null=True)),
                ('outros_sintomas', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('num_endereco', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('ponto_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_acs', models.CharField(blank=True, max_length=100, null=True)),
                ('profis_informante', models.CharField(max_length=100)),
                ('num_pessoas', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_residente', models.CharField(blank=True, max_length=200, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TermoIsolamento.paciente')),
            ],
        ),
    ]
