# Generated by Django 3.1.4 on 2020-12-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermoIsolamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='exame_solicitado',
            field=models.CharField(choices=[('RT-PCR', 'RT-PCR'), ('TR - Anticorpo', 'TR - ANTICORPO'), ('TR - Antígeno', 'TR - ANTÍGENO'), ('Teste Sorológico', 'TESTE SOROLÓGICO')], default='', max_length=50),
        ),
    ]
