# Generated by Django 3.1.5 on 2021-01-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermoIsolamento', '0003_auto_20210106_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
