# Generated by Django 3.1.4 on 2021-01-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TermoIsolamento', '0004_auto_20210106_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='resposavel_pct',
            new_name='responsavel_pct',
        ),
    ]
