# Generated by Django 3.1.5 on 2021-01-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermoIsolamento', '0006_auto_20210114_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='semCPF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residente',
            name='num_pessoas',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
