# Generated by Django 3.1.5 on 2021-01-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermoIsolamento', '0007_auto_20210118_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dt_fim_isolamento',
            field=models.CharField(default='AUTOMÁTICO', max_length=20),
        ),
    ]
