# Generated by Django 3.1.5 on 2021-01-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermoIsolamento', '0009_auto_20210119_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='num_pessoas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='num_pessoas',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
